"""add delete and report functions

Revision ID: 831a9689cf10
Revises: aa991b709b58
Create Date: 2025-08-22 12:27:25.423645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '831a9689cf10'
down_revision = 'aa991b709b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)

    # ### end Alembic commands ###
